import type { GuideContent } from '../../lib/content-types';

type Locale = 'en' | 'sk' | 'de';

const sources = [
  { id: 'gdpr', label: 'Regulation (EU) 2016/679 (GDPR)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj', publisher: 'EUR-Lex' },
  { id: 'scc', label: 'Standard Contractual Clauses for international transfers', url: 'https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en', publisher: 'European Commission' },
  { id: 'edpb', label: 'EDPB recommendations and guidance', url: 'https://www.edpb.europa.eu/our-work-tools/our-documents/recommendations_en', publisher: 'European Data Protection Board' },
  { id: 'regions', label: 'Google Cloud locations', url: 'https://cloud.google.com/about/locations', publisher: 'Google Cloud' },
];

export const dataResidencyGuides: Record<Locale, GuideContent> = {
  en: {
    title: 'Data Residency & GDPR',
    description: 'Keep your AI data and workloads inside the EU. See how EUHub AI designs data-residency boundaries, transfer safeguards and deployment controls for regulated teams.',
    directAnswer: 'EU data residency is a design decision about where workloads, prompts, documents, logs, backups and support access are processed—not a logo on a cloud region. A credible deployment records each data flow, gives the customer a chosen EU, private-cloud or on-premise boundary, and documents any transfer or subprocessor that remains.',
    faqHeading: 'Frequently asked questions',
    sourcesHeading: 'Primary sources',
    citations: sources,
    sections: [
      { heading: 'Start with a data-flow inventory', content: 'For an enterprise buyer, “where do our data go?” is not one question. It includes source systems, uploaded documents, prompt context, embeddings, model requests, telemetry, backups, support access and incident records. Each flow needs an owner, a purpose, a destination, a retention rule and a transfer decision.\n\nEUHub AI designs deployments around the environment selected for the engagement: an EU-only public-cloud region, the customer’s private cloud, or an on-premise environment. The website itself currently runs in Google Cloud europe-west1 in Belgium; customer-system architecture is agreed per project. A deployment design should never imply that all possible customers have identical data paths.' },
      { heading: 'Choose the deployment boundary that matches the risk', content: 'The right boundary depends on the data category, regulatory obligations, internal security model, operational team and model requirements. An EU public-cloud deployment can reduce operational burden while retaining regional control. A private-cloud or on-premise deployment can provide tighter isolation and customer control, but it shifts more operating responsibility to the customer or delivery team.\n\nThe decisive question is not whether a platform says “EU”. It is whether the architecture identifies every processor and subprocessor, records where each category of data is handled, and gives the customer a practical way to test and audit the boundary.', table: { caption: 'Deployment choices to discuss during an AI architecture review', columns: ['Deployment option', 'Typical data boundary', 'Operational responsibility', 'Evidence to request'], rows: [ ['EU public cloud', 'Customer-approved EU region and managed services', 'Shared between customer and delivery team', 'Region diagram, service inventory, access controls'], ['Private cloud', 'Customer-controlled tenancy and network boundary', 'Customer or agreed managed operator', 'Network design, identity model, backup and incident runbook'], ['On-premise', 'Customer site or hardware boundary', 'Customer with defined support responsibilities', 'Hardware baseline, patching, logging and recovery procedure'] ] } },
      { heading: 'DPA, subprocessors and transfer decisions', content: 'Where EUHub AI processes personal data on behalf of a customer, the parties should agree a Data Processing Agreement that reflects the actual processing, roles, instructions, security measures, deletion/return process and audit arrangements. GDPR Article 28 and Article 32 are useful reference points, but the agreement must match the concrete system rather than reuse generic language without review.\n\nSubprocessor transparency is operational: the customer needs a current list of relevant hosting, model, monitoring and support providers, the reason each is used, and a process for notifying changes where the agreement requires it. A self-hosted or on-premise design can reduce some third-party exposure, but it does not remove the need to document administrators, support channels and telemetry.' },
      { heading: 'International transfers require an explicit design', content: 'If a data flow leaves the European Economic Area, treat that as a documented architecture and legal decision. Record the destination, provider role, transfer mechanism, supplementary safeguards and residual risk. Standard Contractual Clauses and transfer-impact assessments can be relevant, but they are not a substitute for understanding the actual technical flow.\n\nThe simplest way to reduce a transfer risk can be to avoid the transfer: keep prompts, documents, logs and model inference inside a selected EU or customer-controlled environment where that is technically and commercially appropriate. Where a flow cannot be avoided, document why, minimize the data and confirm the controls with qualified privacy counsel.' },
      { heading: 'Security, retention and proof for procurement', content: 'A defensible deployment combines encryption in transit and at rest, least-privilege access, role separation, audit logging, monitored backups and an incident process. The actual controls depend on the chosen environment and contract; do not advertise a control that is not part of the delivered design.\n\nFor retention, define what is stored, why it is stored, who can access it, and what triggers deletion or return. A customer should be able to request evidence such as an architecture diagram, access matrix, subprocessor inventory, runbook, log-retention setting, backup policy and deletion procedure. [Request a data-processing architecture review](/en#contact) to map those artifacts before a pilot is approved.' },
    ],
    faqs: [
      { question: 'Can AI prompts and documents remain in the EU?', answer: 'They can when the selected model, hosting, storage, logging and support design support that boundary. The architecture must document each flow rather than relying on a broad regional statement.' },
      { question: 'Do we need a Data Processing Agreement?', answer: 'Where a supplier processes personal data on your behalf, a DPA is commonly required to define the roles, instructions, security expectations, subprocessors, audit rights and deletion or return process. Obtain legal review for your situation.' },
      { question: 'How do we assess subprocessors?', answer: 'Maintain an inventory of hosting, model, monitoring and support providers; identify what data each may receive; record their location and role; and define how customers are informed when the list changes.' },
      { question: 'What happens if a provider needs non-EEA processing?', answer: 'Document the exact flow, destination, purpose, transfer mechanism and safeguards. Minimize the data and obtain privacy/legal review before approving the architecture.' },
      { question: 'Can an on-premise model remove all data-protection work?', answer: 'No. On-premise deployment changes the boundary but does not remove responsibilities for access, logging, retention, security, staff access, incident handling or contractual roles.' },
      { question: 'What evidence should procurement request?', answer: 'Request a data-flow diagram, deployment and region statement, DPA, subprocessor list, access matrix, retention policy, security controls, incident process and documented handover responsibilities.' },
    ],
  },
  sk: {
    title: 'Dátová rezidencia a GDPR',
    description: 'Udržte AI dáta a pracovné záťaže v EÚ. Zistite, ako EUHub AI navrhuje hranice dátovej rezidencie, ochrany pri prenosoch a kontroly nasadenia pre regulované tímy.',
    directAnswer: 'Dátová rezidencia v EÚ je rozhodnutie o tom, kde sa spracúvajú pracovné záťaže, prompty, dokumenty, logy, zálohy a podpora, nie iba označenie cloudového regiónu. Dôveryhodné nasadenie zaznamenáva každý tok dát, umožňuje zákazníkovi zvoliť hranicu v EÚ, privátnom cloude alebo on-premise a dokumentuje každý zostávajúci prenos či subdodávateľa.',
    faqHeading: 'Často kladené otázky',
    sourcesHeading: 'Primárne zdroje',
    citations: sources,
    sections: [
      { heading: 'Začnite inventárom tokov dát', content: 'Pre podnikového zákazníka otázka „kam idú naše dáta?“ nemá jedinú odpoveď. Zahŕňa zdrojové systémy, nahrané dokumenty, kontext promptov, embeddingy, požiadavky na model, telemetriu, zálohy, prístupy podpory aj záznamy incidentov. Každý tok potrebuje vlastníka, účel, cieľ, pravidlo uchovávania a rozhodnutie o prenose.\n\nEUHub AI navrhuje nasadenie podľa prostredia vybraného pre spoluprácu: verejný cloud v regióne EÚ, privátny cloud zákazníka alebo on-premise prostredie. Samotná webstránka beží v Google Cloud europe-west1 v Belgicku; architektúra zákazníckych systémov sa dohodne pre každý projekt. Návrh nasadenia nesmie naznačovať, že všetci zákazníci majú rovnaké dátové toky.' },
      { heading: 'Zvoľte hranicu nasadenia podľa rizika', content: 'Správna hranica závisí od kategórie dát, regulačných povinností, interného bezpečnostného modelu, prevádzkového tímu a požiadaviek na model. Verejný cloud v EÚ môže znížiť prevádzkovú záťaž pri zachovaní regionálnej kontroly. Privátny cloud alebo on-premise môže priniesť silnejšiu izoláciu a kontrolu zákazníka, ale prenáša viac zodpovednosti na zákazníka alebo dohodnutého prevádzkovateľa.\n\nRozhodujúce nie je, či platforma uvádza „EÚ“. Rozhodujúce je, či architektúra identifikuje každého spracovateľa a subdodávateľa, zaznamenáva, kde sa spracúva každá kategória dát, a dáva zákazníkovi praktický spôsob overenia hranice.', table: { caption: 'Možnosti nasadenia na diskusiu pri AI architektonickom review', columns: ['Možnosť', 'Typická hranica dát', 'Prevádzková zodpovednosť', 'Požadovaný dôkaz'], rows: [ ['Verejný cloud v EÚ', 'Zákazníkom schválený región EÚ a spravované služby', 'Zdieľaná medzi zákazníkom a realizačným tímom', 'Diagram regiónu, inventár služieb, prístupové kontroly'], ['Privátny cloud', 'Tenant a sieťová hranica zákazníka', 'Zákazník alebo dohodnutý prevádzkovateľ', 'Sieťový návrh, identita, zálohy a incident runbook'], ['On-premise', 'Priestory alebo hardvér zákazníka', 'Zákazník s definovanou podporou', 'Hardvérový základ, patchovanie, logovanie a obnova'] ] } },
      { heading: 'DPA, subdodávatelia a rozhodnutia o prenosoch', content: 'Ak EUHub AI spracúva osobné údaje v mene zákazníka, strany majú uzavrieť zmluvu o spracúvaní osobných údajov, ktorá zodpovedá reálnemu spracúvaniu, rolám, pokynom, bezpečnostným opatreniam, postupu vymazania alebo vrátenia a auditu. Články 28 a 32 GDPR sú užitočné referencie, no dohoda musí zodpovedať konkrétnemu systému, nie iba opakovať všeobecné texty bez overenia.\n\nTransparentnosť subdodávateľov je prevádzková téma: zákazník potrebuje aktuálny zoznam hostingu, modelov, monitoringu a podpory, dôvod použitia každého z nich a proces oznamovania zmien tam, kde to vyžaduje dohoda. Self-hosted alebo on-premise riešenie môže znížiť časť vystavenia tretím stranám, neodstraňuje však potrebu zdokumentovať administrátorov, podporu a telemetriu.' },
      { heading: 'Medzinárodné prenosy vyžadujú jasný návrh', content: 'Ak tok dát opúšťa Európsky hospodársky priestor, riešte ho ako zdokumentované architektonické aj právne rozhodnutie. Zaznamenajte cieľ, rolu poskytovateľa, mechanizmus prenosu, doplnkové záruky a zvyšné riziko. Štandardné zmluvné doložky a posúdenia dopadu prenosu môžu byť relevantné, nie sú však náhradou za pochopenie reálneho technického toku.\n\nNajjednoduchším spôsobom zníženia rizika je niekedy prenos nevykonať: ponechať prompty, dokumenty, logy a inferenciu modelu vo zvolenom prostredí EÚ alebo pod kontrolou zákazníka, ak je to technicky a obchodne vhodné. Ak sa toku nedá vyhnúť, zdokumentujte dôvod, minimalizujte dáta a potvrďte kontroly s kvalifikovaným právnym poradcom.' },
      { heading: 'Bezpečnosť, uchovávanie a dôkazy pre obstarávanie', content: 'Obhájiteľné nasadenie kombinuje šifrovanie pri prenose aj v úložisku, prístup s najnižšími oprávneniami, oddelenie rolí, auditné logovanie, monitorované zálohy a postup pri incidente. Konkrétne kontroly závisia od prostredia a zmluvy; neuvádzajte kontrolu, ktorá nie je súčasťou dodaného návrhu.\n\nPri uchovávaní definujte, čo sa ukladá, prečo, kto má prístup a čo spustí vymazanie alebo vrátenie. Zákazník si má vedieť vyžiadať diagram architektúry, maticu prístupov, zoznam subdodávateľov, runbook, nastavenie uchovávania logov, politiku záloh a postup vymazania. [Požiadajte o architektonické posúdenie spracúvania dát](/sk#contact), ak chcete tieto artefakty zmapovať pred schválením pilotu.' },
    ],
    faqs: [
      { question: 'Môžu prompty a dokumenty AI zostať v EÚ?', answer: 'Môžu, ak zvolený model, hosting, úložisko, logovanie a podpora túto hranicu podporujú. Architektúra musí zdokumentovať každý tok, nie sa spoliehať na všeobecné regionálne tvrdenie.' },
      { question: 'Potrebujeme zmluvu o spracúvaní osobných údajov?', answer: 'Ak dodávateľ spracúva osobné údaje vo vašom mene, DPA bežne definuje roly, pokyny, bezpečnosť, subdodávateľov, auditné práva a vymazanie alebo vrátenie. Pre vlastnú situáciu si vyžiadajte právne posúdenie.' },
      { question: 'Ako posúdime subdodávateľov?', answer: 'Udržiavajte inventár hostingu, modelov, monitoringu a podpory; určite, aké dáta môže každý dostať; zaznamenajte umiestnenie a rolu; a definujte, ako sa zákazník dozvie o zmenách.' },
      { question: 'Čo ak poskytovateľ potrebuje spracovanie mimo EHP?', answer: 'Zdokumentujte presný tok, cieľ, účel, mechanizmus prenosu a záruky. Dáta minimalizujte a pred schválením architektúry získajte právne alebo privacy review.' },
      { question: 'Odstráni on-premise model všetku prácu s ochranou údajov?', answer: 'Nie. On-premise mení hranicu, ale neodstraňuje zodpovednosť za prístupy, logovanie, uchovávanie, bezpečnosť, prácu zamestnancov, incidenty ani zmluvné roly.' },
      { question: 'Aké dôkazy má vyžiadať obstarávanie?', answer: 'Vyžiadajte diagram tokov dát, vyhlásenie o nasadení a regióne, DPA, zoznam subdodávateľov, maticu prístupov, politiku uchovávania, bezpečnostné kontroly, postup incidentov a zodpovednosť za odovzdanie.' },
    ],
  },
  de: {
    title: 'Datenresidenz & DSGVO',
    description: 'Halten Sie KI-Daten und Workloads in der EU. Erfahren Sie, wie EUHub AI Datenresidenz-Grenzen, Transfer-Schutzmaßnahmen und Deployment-Kontrollen für regulierte Teams entwirft.',
    directAnswer: 'EU-Datenresidenz ist eine Architekturentscheidung darüber, wo Workloads, Prompts, Dokumente, Logs, Backups und Support-Zugriffe verarbeitet werden, nicht nur ein Cloud-Regionslabel. Ein belastbares Deployment dokumentiert jeden Datenfluss, gibt dem Kunden eine gewählte EU-, Private-Cloud- oder On-Premise-Grenze und beschreibt jeden verbleibenden Transfer oder Unterauftragsverarbeiter.',
    faqHeading: 'Häufige Fragen',
    sourcesHeading: 'Primärquellen',
    citations: sources,
    sections: [
      { heading: 'Mit einem Datenfluss-Inventar beginnen', content: 'Für einen Unternehmenskunden ist „Wohin gehen unsere Daten?“ keine einzelne Frage. Sie umfasst Quellsysteme, hochgeladene Dokumente, Prompt-Kontext, Embeddings, Modellanfragen, Telemetrie, Backups, Support-Zugriffe und Incident-Aufzeichnungen. Jeder Fluss braucht Eigentümer, Zweck, Ziel, Aufbewahrungsregel und Transferentscheidung.\n\nEUHub AI entwirft Deployments für die im Engagement ausgewählte Umgebung: eine EU-only Public-Cloud-Region, die Private Cloud des Kunden oder eine On-Premise-Umgebung. Die Website selbst läuft derzeit in Google Cloud europe-west1 in Belgien; die Architektur von Kundensystemen wird projektbezogen vereinbart. Ein Deployment-Design darf nicht suggerieren, dass alle Kunden identische Datenflüsse haben.' },
      { heading: 'Die Deployment-Grenze nach Risiko wählen', content: 'Die passende Grenze hängt von Datenkategorie, regulatorischen Pflichten, internem Sicherheitsmodell, Betriebsteam und Modellanforderungen ab. Eine EU-Public-Cloud kann Betriebsaufwand senken und regionale Kontrolle behalten. Private Cloud oder On-Premise kann stärkere Isolation und Kundenkontrolle bieten, verlagert aber mehr Betriebsverantwortung auf Kunde oder vereinbarten Betreiber.\n\nEntscheidend ist nicht, ob eine Plattform „EU“ sagt. Entscheidend ist, ob die Architektur jeden Auftrags- und Unterauftragsverarbeiter identifiziert, festhält, wo jede Datenkategorie verarbeitet wird, und dem Kunden eine praktische Prüfung der Grenze ermöglicht.', table: { caption: 'Deployment-Optionen für einen KI-Architekturreview', columns: ['Option', 'Typische Datengrenze', 'Betriebsverantwortung', 'Anzufordernder Nachweis'], rows: [ ['EU Public Cloud', 'Kundenseitig freigegebene EU-Region und Managed Services', 'Geteilt zwischen Kunde und Delivery-Team', 'Regionsdiagramm, Service-Inventar, Zugriffskontrollen'], ['Private Cloud', 'Kunden-Tenant und Netzwerkgrenze', 'Kunde oder vereinbarter Betreiber', 'Netzwerkdesign, Identitätsmodell, Backup- und Incident-Runbook'], ['On-Premise', 'Kundenstandort oder Hardwaregrenze', 'Kunde mit definierter Supportverantwortung', 'Hardware-Basis, Patching, Logging und Wiederherstellung'] ] } },
      { heading: 'AVV, Unterauftragsverarbeiter und Transferentscheidungen', content: 'Wenn EUHub AI personenbezogene Daten im Auftrag eines Kunden verarbeitet, sollten die Parteien eine Auftragsverarbeitungsvereinbarung schließen, die tatsächliche Verarbeitung, Rollen, Weisungen, Sicherheitsmaßnahmen, Lösch- oder Rückgabeprozess und Audit-Regelung abbildet. DSGVO Artikel 28 und 32 sind hilfreiche Bezugspunkte, aber die Vereinbarung muss dem konkreten System entsprechen und darf keine ungeprüften Allgemeinplätze wiederholen.\n\nUnterauftragsverarbeiter-Transparenz ist operativ: Der Kunde benötigt eine aktuelle Liste relevanter Hosting-, Modell-, Monitoring- und Supportanbieter, den Grund für deren Einsatz und einen Prozess zur Benachrichtigung über Änderungen, wenn die Vereinbarung dies verlangt. Self-hosted oder On-Premise kann die Exposition gegenüber Dritten reduzieren, beseitigt aber nicht die Pflicht, Administratoren, Supportkanäle und Telemetrie zu dokumentieren.' },
      { heading: 'Internationale Transfers benötigen ein explizites Design', content: 'Verlässt ein Datenfluss den Europäischen Wirtschaftsraum, behandeln Sie ihn als dokumentierte Architektur- und Rechtsentscheidung. Erfassen Sie Ziel, Providerrolle, Transfermechanismus, ergänzende Schutzmaßnahmen und Restrisiko. Standardvertragsklauseln und Transfer Impact Assessments können relevant sein, ersetzen aber nicht das Verständnis des tatsächlichen technischen Flusses.\n\nDer einfachste Weg, ein Transferrisiko zu verringern, kann sein, den Transfer zu vermeiden: Prompts, Dokumente, Logs und Model Inference in einer gewählten EU- oder kundenverwalteten Umgebung zu halten, wenn dies technisch und wirtschaftlich passend ist. Ist ein Fluss unvermeidbar, dokumentieren Sie den Grund, minimieren Sie die Daten und bestätigen Sie die Kontrollen mit qualifizierter Datenschutzberatung.' },
      { heading: 'Sicherheit, Aufbewahrung und Nachweise für die Beschaffung', content: 'Ein vertretbares Deployment kombiniert Verschlüsselung bei Übertragung und Speicherung, Least-Privilege-Zugriff, Rollentrennung, Audit-Logging, überwachte Backups und einen Incident-Prozess. Die konkreten Kontrollen hängen von Umgebung und Vertrag ab; bewerben Sie keine Kontrolle, die nicht Teil des gelieferten Designs ist.\n\nFür die Aufbewahrung definieren Sie, was gespeichert wird, warum, wer Zugriff hat und wodurch Löschung oder Rückgabe ausgelöst wird. Ein Kunde sollte Architekturdiagramm, Zugriffsmatrix, Unterauftragsverarbeiter-Inventar, Runbook, Log-Retention-Einstellung, Backup-Policy und Löschverfahren anfordern können. [Fordern Sie einen Architekturreview für Datenverarbeitung an](/de#contact), wenn diese Artefakte vor einer Pilotfreigabe erfasst werden sollen.' },
    ],
    faqs: [
      { question: 'Können KI-Prompts und Dokumente in der EU bleiben?', answer: 'Ja, wenn das ausgewählte Modell, Hosting, Storage, Logging und Support diese Grenze unterstützen. Die Architektur muss jeden Datenfluss dokumentieren und darf sich nicht auf eine allgemeine Regionsaussage verlassen.' },
      { question: 'Benötigen wir eine Auftragsverarbeitungsvereinbarung?', answer: 'Wenn ein Anbieter personenbezogene Daten in Ihrem Auftrag verarbeitet, definiert eine AVV typischerweise Rollen, Weisungen, Sicherheit, Unterauftragsverarbeiter, Auditrechte sowie Löschung oder Rückgabe. Lassen Sie Ihre konkrete Situation rechtlich prüfen.' },
      { question: 'Wie bewerten wir Unterauftragsverarbeiter?', answer: 'Führen Sie ein Inventar von Hosting, Modellen, Monitoring und Support; bestimmen Sie, welche Daten jeder erhalten kann; erfassen Sie Standort und Rolle; und definieren Sie, wie Kunden über Änderungen informiert werden.' },
      { question: 'Was passiert bei Verarbeitung außerhalb des EWR?', answer: 'Dokumentieren Sie exakten Fluss, Ziel, Zweck, Transfermechanismus und Schutzmaßnahmen. Minimieren Sie die Daten und holen Sie Datenschutz- oder Rechtsreview ein, bevor die Architektur freigegeben wird.' },
      { question: 'Entfernt ein On-Premise-Modell alle Datenschutzaufgaben?', answer: 'Nein. On-Premise verändert die Grenze, beseitigt aber nicht Verantwortlichkeiten für Zugriffe, Logging, Aufbewahrung, Sicherheit, Mitarbeiterzugriff, Incident Handling oder Vertragsrollen.' },
      { question: 'Welche Nachweise sollte die Beschaffung verlangen?', answer: 'Fordern Sie Datenflussdiagramm, Deployment- und Regionsstatement, AVV, Unterauftragsverarbeiterliste, Zugriffsmatrix, Aufbewahrungsrichtlinie, Sicherheitskontrollen, Incident-Prozess und Übergabeverantwortlichkeiten an.' },
    ],
  },
};
