import type { GuideContent } from '../../lib/content-types';

type Locale = 'en' | 'sk' | 'de';

export const portabilityGuides: Record<Locale, GuideContent> = {
  en: {
    title: 'You own it. No lock-in.',
    description: 'No vendor lock-in: own your models, data and workflows outright. EUHub AI builds portable AI systems you can export and operate in your chosen EU environment.',
    directAnswer: 'A portable AI system keeps your data, prompts, source code, evaluation assets and deployment configuration under terms you can inspect and export. It does not mean every component is interchangeable overnight; it means the dependencies, formats and handover responsibilities are designed and documented before a vendor change becomes urgent.',
    faqHeading: 'Frequently asked questions',
    sections: [
      { heading: 'What vendor-neutral AI means in practice', content: 'Vendor neutrality is an engineering and commercial discipline, not a promise that every model produces identical answers. We separate the business workflow from the model provider, record the prompt and retrieval configuration, use documented interfaces, and make ownership explicit in the engagement documents. That gives a customer a repeatable way to evaluate another model or operator without reconstructing the system from screenshots and tribal knowledge.\n\nA good portability review begins with a concrete question: if the current provider, cloud region or delivery partner changed next quarter, what data, credentials, code, tests and runbooks would the customer receive, in what format, and who would be able to operate them? If that answer is unclear, the dependency is not yet manageable.' },
      { heading: 'Design the boundaries before selecting a model', content: 'Model choice should be replaceable behind a narrow application interface. The workflow defines inputs, permissions, retrieval policy, tool calls, approval steps and success criteria; the model is one evaluated implementation of that interface. Retrieval indexes, workflow state and audit logs also need explicit ownership and export paths.\n\n• Store prompts, policies and configuration in version control rather than only in a provider console.\n• Keep evaluation cases and expected outcomes with the customer-controlled delivery repository.\n• Use documented API contracts for ERP, CRM, document and messaging integrations.\n• Record model, embedding, vector-store and orchestration versions in deployment manifests.\n• Encrypt credentials and rotate them through the customer-approved secret-management process.\n\nThis approach does not ban managed services. It makes the reason for each managed service visible, evaluates the switching cost, and defines the evidence needed to leave safely.' },
      { heading: 'Portability evidence to request during procurement', content: 'Ask for evidence rather than assurances. A supplier should be able to show the data export format, infrastructure definition, repository ownership, evaluation harness and handover checklist before production launch. The strongest evidence is a short, documented restore or migration exercise performed on a non-production environment.\n\nA contract should distinguish custom deliverables from third-party licenses. Open-source components, hosted model access, cloud accounts and proprietary vendor features have different transfer rules. The customer needs a clear inventory of each component, its owner, its license, its renewal boundary and the procedure required to replace it.' , table: { caption: 'Questions that expose portability risk before launch', columns: ['Area', 'Portable implementation', 'Evidence to request'], rows: [ ['Models', 'A documented provider interface and evaluation set', 'Model-selection record and switch test'], ['Prompts and policies', 'Version-controlled, customer-accessible configuration', 'Repository access and release history'], ['Data and retrieval', 'Documented export formats and index rebuild process', 'Sample export and restore runbook'], ['Deployment', 'Container and infrastructure definitions for the chosen environment', 'Build instructions and infrastructure-as-code'], ['Operations', 'Named monitoring, incident and handover responsibilities', 'Runbook, access matrix and exit checklist'] ] } },
      { heading: 'How a controlled model switch works', content: 'A model switch should be a measured change, not an emergency cutover. First, freeze a representative evaluation set covering routine requests, edge cases, unsafe inputs and business approvals. Run the current and candidate models against the same retrieval context and tools. Compare accuracy, citation behavior, latency, cost, safety failures and human-review workload.\n\nNext, decide whether the new model can be adopted without workflow changes. If it cannot, treat the difference as a product change and route it through the same change-control process as an ERP or CRM integration. Keep the previous configuration available until the customer accepts the outcome. This makes a switch auditable and protects day-to-day operations from a silent quality regression.' },
      { heading: 'A handover should be usable on day one', content: 'Exit-friendly delivery includes more than a zip file. The receiving team needs readable source code, deployment artifacts, environment documentation, data-processing boundaries, test data rules, known limitations, contact handover and a prioritized backlog. A practical handover session proves that an authorized customer engineer can deploy a non-production instance, run the evaluation set, inspect logs and rotate credentials.\n\nEUHub AI can map these requirements during the diagnostic phase, then turn them into acceptance criteria for a pilot or scale engagement. [Request a diagnostic audit](/en#contact) if you want the portability risk of an existing AI system assessed before a renewal or migration decision.' },
    ],
    faqs: [
      { question: 'Can we change LLM providers later?', answer: 'Yes, when the workflow, prompts, evaluation set and tool integrations are separated from a single provider API. A change still requires testing because models differ in behavior, latency, safety controls and cost.' },
      { question: 'Do we own the prompts and configurations?', answer: 'Ownership should be explicit in the agreement and reflected in repository access. A usable answer includes the version history, deployment settings and the documentation needed to operate the configuration.' },
      { question: 'Can we export a vector database?', answer: 'The answer depends on the selected store and data model. Before launch, agree the export format, embedding rebuild procedure, metadata retention rules and the time required to restore a usable index.' },
      { question: 'What does a safe handover include?', answer: 'A safe handover includes source, deployment instructions, access ownership, runbooks, evaluation assets, data-boundary documentation and a working non-production handover exercise.' },
      { question: 'Does portability prevent using managed cloud services?', answer: 'No. Managed services can be appropriate when their benefits and switching cost are known. Portability means recording the dependency and having a credible replacement or exit procedure.' },
      { question: 'How do we prove a system is portable?', answer: 'Use an evidence-based exercise: export representative data, deploy a non-production environment from documented artifacts, run the evaluation set and confirm that authorized customer staff can operate the result.' },
    ],
  },
  sk: {
    title: 'Vlastníte to. Žiadna závislosť od dodávateľa.',
    description: 'Žiadna závislosť od dodávateľa: vlastníte modely, dáta aj procesy. EUHub AI navrhuje prenositeľné AI systémy, ktoré môžete exportovať a prevádzkovať vo zvolenom prostredí v EÚ.',
    directAnswer: 'Prenositeľný AI systém ponecháva vaše dáta, prompty, zdrojový kód, hodnotiace podklady a konfiguráciu nasadenia pod podmienkami, ktoré môžete kontrolovať a exportovať. Neznamená to, že každý komponent vymeníte cez noc; znamená to, že závislosti, formáty a zodpovednosti za odovzdanie sú navrhnuté skôr, než sa zmena dodávateľa stane naliehavou.',
    faqHeading: 'Často kladené otázky',
    sections: [
      { heading: 'Čo v praxi znamená AI bez závislosti od dodávateľa', content: 'Nezávislosť od dodávateľa je technická aj obchodná disciplína, nie prísľub, že každý model dá rovnakú odpoveď. Obchodný proces oddeľujeme od poskytovateľa modelu, zaznamenávame konfiguráciu promptov a vyhľadávania, používame zdokumentované rozhrania a vlastníctvo riešime priamo v dokumentoch k spolupráci. Zákazník tak môže vyhodnotiť iný model alebo prevádzkovateľa bez toho, aby systém znovu skladal zo snímok obrazovky a neformálnych znalostí.\n\nDobrá kontrola prenositeľnosti začína konkrétnou otázkou: ak by sa budúci štvrťrok zmenil poskytovateľ, cloudový región alebo dodávateľ, aké dáta, prístupy, kód, testy a prevádzkové postupy zákazník dostane, v akom formáte a kto ich bude vedieť používať? Ak odpoveď nie je jasná, závislosť ešte nie je zvládnutá.' },
      { heading: 'Hranice riešenia navrhnite pred výberom modelu', content: 'Výber modelu má byť vymeniteľný za úzkym aplikačným rozhraním. Proces určuje vstupy, oprávnenia, pravidlá vyhľadávania, volania nástrojov, schvaľovanie a kritériá úspechu; model je iba jedna vyhodnotená implementácia tohto rozhrania. Aj vyhľadávacie indexy, stav procesu a auditné záznamy potrebujú jasné vlastníctvo a postup exportu.\n\n• Prompty, pravidlá a konfiguráciu ukladajte do verzionovania, nie iba do konzoly dodávateľa.\n• Hodnotiace prípady a očakávané výsledky ponechajte v repozitári pod kontrolou zákazníka.\n• Pre integrácie ERP, CRM, dokumentov a správ používajte zdokumentované API kontrakty.\n• Verzie modelu, embeddingov, vektorového úložiska a orchestrace zaznamenajte v manifestačných súboroch.\n• Prihlasovacie údaje šifrujte a rotujte cez zákazníkom schválené spravovanie tajomstiev.\n\nTento prístup nezakazuje spravované služby. Zviditeľňuje dôvod ich použitia, hodnotí náklady na zmenu a určuje dôkazy potrebné na bezpečný odchod.' },
      { heading: 'Dôkazy o prenositeľnosti pri obstarávaní', content: 'Pýtajte si dôkazy, nie uistenia. Dodávateľ by mal pred spustením produkcie vedieť ukázať formát exportu dát, definíciu infraštruktúry, vlastníctvo repozitára, hodnotiaci rámec a kontrolný zoznam odovzdania. Najsilnejším dôkazom je krátke zdokumentované obnovenie alebo migrácia v neprodukčnom prostredí.\n\nZmluva musí rozlišovať vlastné výstupy od licencií tretích strán. Open-source komponenty, prístup k hostovanému modelu, cloudové účty a proprietárne funkcie majú rozdielne pravidlá prevodu. Zákazník potrebuje jasný inventár komponentov, vlastníka, licencie, hranice obnovy a postup nahradenia.' , table: { caption: 'Otázky, ktoré pred spustením odhalia riziko závislosti', columns: ['Oblasť', 'Prenositeľné riešenie', 'Požadovaný dôkaz'], rows: [ ['Modely', 'Zdokumentované rozhranie poskytovateľa a hodnotiaca sada', 'Záznam výberu modelu a test zmeny'], ['Prompty a pravidlá', 'Verzionovaná konfigurácia prístupná zákazníkovi', 'Prístup k repozitáru a história vydaní'], ['Dáta a vyhľadávanie', 'Zdokumentované formáty exportu a obnova indexu', 'Ukážkový export a prevádzkový postup'], ['Nasadenie', 'Kontajnery a definície infraštruktúry', 'Návod na build a infrastructure-as-code'], ['Prevádzka', 'Pomenované zodpovednosti za monitoring a odovzdanie', 'Runbook, matica prístupov a exit checklist'] ] } },
      { heading: 'Ako funguje riadená zmena modelu', content: 'Zmena modelu má byť meraná zmena, nie núdzové prepnutie. Najprv zmrazte reprezentatívnu hodnotiacu sadu s bežnými požiadavkami, hraničnými prípadmi, nebezpečnými vstupmi a obchodným schvaľovaním. Aktuálny a kandidátsky model spúšťajte nad rovnakým kontextom, vyhľadávaním a nástrojmi. Porovnajte správnosť, prácu so zdrojmi, odozvu, cenu, bezpečnostné zlyhania a objem ľudskej kontroly.\n\nPotom rozhodnite, či nový model funguje bez zmeny procesu. Ak nie, ide o produktovú zmenu a má prejsť rovnakým riadením ako integrácia ERP alebo CRM. Predchádzajúcu konfiguráciu ponechajte dostupnú, kým zákazník výsledok neschváli. Takáto zmena je auditovateľná a chráni prevádzku pred tichým poklesom kvality.' },
      { heading: 'Odovzdanie musí byť použiteľné hneď prvý deň', content: 'Odovzdanie priateľské k odchodu nie je iba archív súborov. Preberajúci tím potrebuje čitateľný zdrojový kód, artefakty nasadenia, dokumentáciu prostredia, hranice spracúvania dát, pravidlá testovacích dát, známe obmedzenia, kontakty a prioritizovaný backlog. Praktické odovzdanie overí, že autorizovaný inžinier zákazníka dokáže nasadiť neprodukčnú inštanciu, spustiť hodnotiacu sadu, skontrolovať logy a rotovať prístupy.\n\nEUHub AI vie tieto požiadavky zmapovať počas diagnostiky a premeniť ich na akceptačné kritériá pre pilot alebo škálovanie. [Požiadajte o diagnostický audit](/sk#contact), ak chcete preveriť riziko závislosti existujúceho AI systému pred obnovou zmluvy alebo rozhodnutím o migrácii.' },
    ],
    faqs: [
      { question: 'Môžeme neskôr zmeniť poskytovateľa LLM?', answer: 'Áno, ak sú proces, prompty, hodnotiaca sada a integrácie nástrojov oddelené od jedného API poskytovateľa. Zmena však vyžaduje testovanie, pretože modely sa líšia správaním, odozvou, bezpečnostnými kontrolami a cenou.' },
      { question: 'Vlastníme prompty a konfigurácie?', answer: 'Vlastníctvo musí byť výslovne uvedené v dohode a potvrdené prístupom k repozitáru. Použiteľná odpoveď zahŕňa históriu verzií, nastavenia nasadenia a dokumentáciu potrebnú na prevádzku.' },
      { question: 'Vieme exportovať vektorovú databázu?', answer: 'Záleží na zvolenom úložisku a dátovom modeli. Pred spustením si dohodnite formát exportu, postup obnovy embeddingov, pravidlá metadata a čas potrebný na vytvorenie použiteľného indexu.' },
      { question: 'Čo obsahuje bezpečné odovzdanie?', answer: 'Bezpečné odovzdanie obsahuje zdrojový kód, postupy nasadenia, vlastníctvo prístupov, runbooky, hodnotiace podklady, dokumentáciu hraníc dát a fungujúce neprodukčné overenie.' },
      { question: 'Bráni prenositeľnosť používaniu spravovaného cloudu?', answer: 'Nie. Spravované služby môžu byť vhodné, ak poznáte ich prínosy a náklady na zmenu. Prenositeľnosť znamená zaznamenať závislosť a mať dôveryhodný postup nahradenia alebo odchodu.' },
      { question: 'Ako dokážeme, že systém je prenositeľný?', answer: 'Vykonajte overenie založené na dôkazoch: exportujte reprezentatívne dáta, nasadzujte neprodukčné prostredie zo zdokumentovaných artefaktov, spustite hodnotiacu sadu a potvrďte, že autorizovaný tím zákazníka výsledok vie prevádzkovať.' },
    ],
  },
  de: {
    title: 'Es gehört Ihnen. Keine Anbieterabhängigkeit.',
    description: 'Keine Anbieterabhängigkeit: Modelle, Daten und Workflows bleiben in Ihrem Besitz. EUHub AI entwickelt portable KI-Systeme, die Sie exportieren und in Ihrer gewählten EU-Umgebung betreiben können.',
    directAnswer: 'Ein portables KI-System hält Daten, Prompts, Quellcode, Evaluierungsunterlagen und Deployment-Konfiguration unter Bedingungen, die Sie prüfen und exportieren können. Das bedeutet nicht, dass jeder Baustein über Nacht austauschbar ist. Es bedeutet, dass Abhängigkeiten, Formate und Übergabepflichten geklärt sind, bevor ein Anbieterwechsel dringend wird.',
    faqHeading: 'Häufige Fragen',
    sections: [
      { heading: 'Was anbieterneutrale KI praktisch bedeutet', content: 'Anbieterneutralität ist eine technische und kommerzielle Disziplin, kein Versprechen identischer Antworten aller Modelle. Wir trennen den Geschäftsworkflow vom Modellanbieter, dokumentieren Prompt- und Retrieval-Konfigurationen, verwenden dokumentierte Schnittstellen und regeln Eigentum in den Engagement-Unterlagen. So kann ein Kunde einen anderen Modellanbieter oder Betreiber bewerten, ohne das System aus Screenshots und implizitem Wissen rekonstruieren zu müssen.\n\nEine gute Portabilitätsprüfung beginnt mit einer konkreten Frage: Wenn sich im nächsten Quartal Anbieter, Cloud-Region oder Delivery-Partner ändern, welche Daten, Zugänge, Codebestände, Tests und Runbooks erhält der Kunde, in welchem Format und wer kann sie betreiben? Ist diese Antwort unklar, ist die Abhängigkeit noch nicht beherrscht.' },
      { heading: 'Grenzen vor der Modellauswahl entwerfen', content: 'Die Modellauswahl sollte hinter einer schmalen Anwendungsschnittstelle austauschbar sein. Der Workflow definiert Eingaben, Berechtigungen, Retrieval-Regeln, Tool-Aufrufe, Freigaben und Erfolgskriterien; das Modell ist eine bewertete Implementierung dieser Schnittstelle. Auch Suchindizes, Workflow-Zustand und Audit-Protokolle benötigen eindeutiges Eigentum und einen Exportweg.\n\n• Prompts, Richtlinien und Konfigurationen gehören in Versionsverwaltung, nicht nur in eine Anbieter-Konsole.\n• Evaluierungsfälle und erwartete Ergebnisse bleiben im kundenverwalteten Repository.\n• Für ERP-, CRM-, Dokumenten- und Messaging-Integrationen werden dokumentierte API-Verträge verwendet.\n• Versionen von Modell, Embeddings, Vektor-Store und Orchestrierung werden in Deployment-Manifesten festgehalten.\n• Zugangsdaten werden verschlüsselt und über das vom Kunden freigegebene Secret-Management rotiert.\n\nDieser Ansatz verbietet keine Managed Services. Er macht ihren Zweck sichtbar, bewertet Wechselkosten und legt die Nachweise für einen sicheren Ausstieg fest.' },
      { heading: 'Portabilitätsnachweise in der Beschaffung', content: 'Fordern Sie Nachweise statt Zusicherungen. Ein Anbieter sollte vor dem Produktionsstart Datenexportformat, Infrastrukturdefinition, Repository-Eigentum, Evaluierungsharness und Übergabecheckliste zeigen können. Der stärkste Nachweis ist eine kurze dokumentierte Wiederherstellung oder Migration in einer Nichtproduktionsumgebung.\n\nEin Vertrag muss kundenspezifische Deliverables von Lizenzen Dritter unterscheiden. Open-Source-Komponenten, gehosteter Modellzugang, Cloud-Konten und proprietäre Features haben unterschiedliche Übertragungsregeln. Der Kunde benötigt ein klares Inventar jeder Komponente, ihres Eigentümers, ihrer Lizenz, ihrer Verlängerungsgrenze und ihres Ersatzverfahrens.', table: { caption: 'Fragen, die Lock-in-Risiken vor dem Start sichtbar machen', columns: ['Bereich', 'Portable Umsetzung', 'Anzufordernder Nachweis'], rows: [ ['Modelle', 'Dokumentierte Provider-Schnittstelle und Evaluierungsset', 'Modellauswahlprotokoll und Wechseltest'], ['Prompts und Richtlinien', 'Versionierte, kundenzugängliche Konfiguration', 'Repository-Zugang und Release-Historie'], ['Daten und Retrieval', 'Dokumentierte Exportformate und Index-Rebuild', 'Beispielexport und Wiederherstellungs-Runbook'], ['Deployment', 'Container und Infrastrukturdefinitionen', 'Build-Anleitung und Infrastructure-as-Code'], ['Betrieb', 'Benannte Monitoring- und Übergabeverantwortung', 'Runbook, Zugriffsmatrix und Exit-Checkliste'] ] } },
      { heading: 'Wie ein kontrollierter Modellwechsel funktioniert', content: 'Ein Modellwechsel sollte eine gemessene Änderung und kein Notfall-Cutover sein. Frieren Sie zuerst ein repräsentatives Evaluierungsset mit Routineanfragen, Grenzfällen, unsicheren Eingaben und geschäftlichen Freigaben ein. Führen Sie aktuelles und Kandidatenmodell mit identischem Retrieval-Kontext und denselben Tools aus. Vergleichen Sie Korrektheit, Quellenverhalten, Latenz, Kosten, Sicherheitsfehler und menschlichen Prüfaufwand.\n\nEntscheiden Sie anschließend, ob das neue Modell ohne Workflow-Änderung eingesetzt werden kann. Falls nicht, behandeln Sie die Differenz als Produktänderung und steuern sie wie eine ERP- oder CRM-Integration. Die vorherige Konfiguration bleibt verfügbar, bis der Kunde das Ergebnis akzeptiert. So bleibt der Wechsel auditierbar und schützt den Betrieb vor einem stillen Qualitätsverlust.' },
      { heading: 'Eine Übergabe muss am ersten Tag nutzbar sein', content: 'Eine ausstiegsfreundliche Übergabe ist mehr als ein ZIP-Archiv. Das übernehmende Team benötigt lesbaren Quellcode, Deployment-Artefakte, Umgebungsdokumentation, Datenverarbeitungsgrenzen, Regeln für Testdaten, bekannte Einschränkungen, Kontaktübergabe und einen priorisierten Backlog. Eine praktische Übergabe beweist, dass ein autorisierter Kundeningenieur eine Nichtproduktionsinstanz bereitstellen, das Evaluierungsset ausführen, Logs prüfen und Zugangsdaten rotieren kann.\n\nEUHub AI kann diese Anforderungen während der Diagnose erfassen und in Abnahmekriterien für Pilot oder Skalierung übersetzen. [Fordern Sie einen diagnostischen Audit an](/de#contact), wenn Sie das Lock-in-Risiko eines bestehenden KI-Systems vor Verlängerung oder Migration bewerten möchten.' },
    ],
    faqs: [
      { question: 'Können wir den LLM-Anbieter später wechseln?', answer: 'Ja, wenn Workflow, Prompts, Evaluierungsset und Tool-Integrationen von einer einzelnen Provider-API getrennt sind. Ein Wechsel erfordert dennoch Tests, weil Modelle sich bei Verhalten, Latenz, Sicherheitskontrollen und Kosten unterscheiden.' },
      { question: 'Gehören uns Prompts und Konfigurationen?', answer: 'Das Eigentum muss im Vertrag ausdrücklich geregelt und durch Repository-Zugang sichtbar sein. Eine brauchbare Antwort umfasst Versionshistorie, Deployment-Einstellungen und die für den Betrieb nötige Dokumentation.' },
      { question: 'Können wir eine Vektordatenbank exportieren?', answer: 'Das hängt vom gewählten Store und Datenmodell ab. Vereinbaren Sie vor dem Start Exportformat, Rebuild-Verfahren für Embeddings, Metadatenregeln und den Zeitraum bis zu einem nutzbaren Index.' },
      { question: 'Was umfasst eine sichere Übergabe?', answer: 'Eine sichere Übergabe umfasst Quellcode, Deployment-Anleitungen, Zugriffsverantwortung, Runbooks, Evaluierungsunterlagen, Daten-Grenzdokumentation und einen funktionierenden Nichtproduktionsnachweis.' },
      { question: 'Verhindert Portabilität die Nutzung von Managed Cloud Services?', answer: 'Nein. Managed Services können sinnvoll sein, wenn Nutzen und Wechselkosten bekannt sind. Portabilität heißt, die Abhängigkeit zu dokumentieren und ein glaubwürdiges Ersatz- oder Ausstiegsverfahren zu besitzen.' },
      { question: 'Wie weisen wir die Portabilität eines Systems nach?', answer: 'Führen Sie eine nachweisbasierte Übung durch: repräsentative Daten exportieren, eine Nichtproduktionsumgebung aus dokumentierten Artefakten bereitstellen, das Evaluierungsset ausführen und bestätigen, dass autorisierte Kundenteams das Ergebnis betreiben können.' },
    ],
  },
};
